sudo: required
dist: trusty

compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            - libfreetype6-dev
            - nvidia-cg-toolkit
            - libfreeimage-dev
            - zlib1g-dev
            - libzzip-dev
            - libois-dev
            - libcppunit-dev
            - doxygen
            - libxt-dev
            - libxaw7-dev
            - libxxf86vm-dev
            - libxrandr-dev
            - libglu-dev
            - libboost-date-time-dev
            - libboost-thread-dev
            - libboost-filesystem-dev
            - cmake
            - g++-4.8
cache:
    directories:
        - node_modules
        - dependencies

before_script:
    - travis_retry npm install bower
    - travis_retry ./node_modules/bower/bin/bower install --config.interactive=false
    - travis_wait cmake -H. -B./hard.build
    - cd ./hard.build

script:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - travis_wait make

notifications:
    email: false
    irc:
        channels:
            - "chat.freenode.net#hardwar"
        template:
            - "\x02%{repository}\x0f#\x0312%{build_number}\x0f (\x0307%{branch}\x0f - \x02%{commit}\x0f : \x0303%{author}\x0f): \x02%{message}\x0f"
            - "Build details : \x0302%{build_url}\x0f"
        on_success: change
        on_failure: always
