# Find MyGUI includes and library
#
# This module defines
#  MyGUI_INCLUDE_DIR
#  MyGUI_LIBRARIES, the libraries to link against to use MyGUI.
#  MyGUI_LIB_DIR, the location of the libraries
#  MyGUI_FOUND, If false, do not try to use MyGUI
#
# Copyright © 2009, Andrew Fenn
#
# Redistribution and use is allowed according to the terms of the BSD license.
# For details see the accompanying COPYING-CMAKE-SCRIPTS file.

IF (MyGUI_LIBRARIES AND MyGUI_INCLUDE_DIR)
	SET(MyGUI_FIND_QUIETLY TRUE) # Already in cache, be silent
ENDIF (MyGUI_LIBRARIES AND MyGUI_INCLUDE_DIR)

IF (WIN32) #Windows
	IF (MyGUISOURCE)
		# you're screwed
	ENDIF (MyGUISOURCE)
ELSE (WIN32) #Unix
	CMAKE_MINIMUM_REQUIRED(VERSION 2.4.7 FATAL_ERROR)
	FIND_PACKAGE(PkgConfig)
	PKG_SEARCH_MODULE(MyGUI MyGUI)
	SET(MyGUI_INCLUDE_DIR ${MyGUI_INCLUDE_DIRS})
	SET(MyGUI_LIB_DIR ${MyGUI_LIBDIR})
	SET(MyGUI_LIBRARIES ${MyGUI_LIBRARIES} CACHE STRING "")
ENDIF (WIN32)

#Do some preparation
SEPARATE_ARGUMENTS(MyGUI_INCLUDE_DIR)
SEPARATE_ARGUMENTS(MyGUI_LIBRARIES)

SET(MyGUI_INCLUDE_DIR ${MyGUI_INCLUDE_DIR} CACHE PATH "")
SET(MyGUI_LIBRARIES ${MyGUI_LIBRARIES} CACHE STRING "")
SET(MyGUI_LIB_DIR ${MyGUI_LIB_DIR} CACHE PATH "")

IF (MyGUI_INCLUDE_DIR AND MyGUI_LIBRARIES)
	SET(MyGUI_FOUND TRUE)
ENDIF (MyGUI_INCLUDE_DIR AND MyGUI_LIBRARIES)

IF (MyGUI_FOUND)
	IF (NOT MyGUI_FIND_QUIETLY)
		MESSAGE(STATUS "  libraries : ${MyGUI_LIBRARIES} from ${MyGUI_LIB_DIR}")
		MESSAGE(STATUS "  includes  : ${MyGUI_INCLUDE_DIR}")
	ENDIF (NOT MyGUI_FIND_QUIETLY)
ELSE (MyGUI_FOUND)
	IF (MyGUI_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find MyGUI")
	ENDIF (MyGUI_FIND_REQUIRED)
ENDIF (MyGUI_FOUND)
