macro(MACRO_FIND_LIBRARIES _package _components)
   FIND_PACKAGE(${_package} COMPONENTS ${_components} REQUIRED)
   __MACRO_FIND_LIBRARY(${_package})
endmacro ()

macro(MACRO_FIND_LIBRARY _package)
   FIND_PACKAGE(${_package} REQUIRED)
   __MACRO_FIND_LIBRARY(${_package})
endmacro ()

macro(__MACRO_FIND_LIBRARY _package)
   if (${_package}_FOUND)
      INCLUDE_DIRECTORIES(${${_package}_INCLUDE_DIR})
      INCLUDE_DIRECTORIES(${${_package}_INCLUDE_DIRS})
      LINK_DIRECTORIES(${${_package}_LIBRARY_DIRS})

      message(STATUS "${_package} Found")
      if (${_package}_LIBRARY)
         message(STATUS "  library : ${${_package}_LIBRARY}")
      endif ()
      message(STATUS "  includes  : ${${_package}_INCLUDE_DIR}")
   else ()
      message(ERROR "\t${_package} not found.\n")
   endif ()
endmacro ()

macro(MACRO_ADD_LIBRARY _package _binary)
   if (${_package}_FOUND)
      TARGET_LINK_LIBRARIES(${_binary} ${${_package}_LIBRARIES})
      TARGET_LINK_LIBRARIES(${_binary} ${${_package}_LIBRARY})
   endif ()
endmacro ()
